import { PrismaClient } from '@prisma/client';
import slugify from 'slugify';
import { CreateBookingDto } from 'src/bookings/dto/create-booking.dto';
const prisma = new PrismaClient();

const booking: CreateBookingDto[] = [
  {
    user_id: 1,
    branch_id: 1,
    stage_id: 1,
    company_name: 'Công ty A',
    email: 'congtya@gmail.com',
    phone: '123456789',
    name: 'Tiệc sinh nhật',
    note: 'Ghi chú',
    number_of_guests: 500,
    organization_date: '2024-12-12T00:00:00.000Z',
    party_type_id: 1,
    shift: 'Sáng',
  },
  {
    user_id: 2,
    branch_id: 1,
    stage_id: 1,
    company_name: 'Công ty B',
    email: 'congtyb@gmail.com',
    phone: '123456789',
    name: 'Tiệc kỷ niệm',
    note: 'Ghi chú',
    number_of_guests: 300,
    organization_date: '2024-01-15T00:00:00.000Z',
    party_type_id: 1,
    shift: 'Tối',
  },
  {
    user_id: 3,
    branch_id: 1,
    stage_id: 1,
    company_name: 'Công ty C',
    email: 'congtyc@gmail.com',
    phone: '123456789',
    name: 'Họp mặt',
    note: 'Ghi chú',
    number_of_guests: 150,
    organization_date: '2024-02-20T00:00:00.000Z',
    party_type_id: 1,
    shift: 'Sáng',
  },
  {
    user_id: 4,
    branch_id: 1,
    stage_id: 1,
    company_name: 'Công ty D',
    email: 'congtyd@gmail.com',
    phone: '123456789',
    name: 'Tiệc Giáng sinh',
    note: 'Ghi chú',
    number_of_guests: 200,
    organization_date: '2024-03-25T00:00:00.000Z',
    party_type_id: 1,
    shift: 'Tối',
  },
  {
    user_id: 5,
    branch_id: 1,
    stage_id: 1,
    company_name: 'Công ty E',
    email: 'congtye@gmail.com',
    phone: '123456789',
    name: 'Tiệc Tất niên',
    note: 'Ghi chú',
    number_of_guests: 400,
    organization_date: '2024-04-10T00:00:00.000Z',
    party_type_id: 1,
    shift: 'Sáng',
  },
  {
    user_id: 6,
    branch_id: 1,
    stage_id: 1,
    company_name: 'Công ty F',
    email: 'congtyf@gmail.com',
    phone: '123456789',
    name: 'Hội thảo',
    note: 'Ghi chú',
    number_of_guests: 250,
    organization_date: '2024-05-05T00:00:00.000Z',
    party_type_id: 1,
    shift: 'Tối',
  },
  {
    user_id: 7,
    branch_id: 1,
    stage_id: 1,
    company_name: 'Công ty G',
    email: 'congtyg@gmail.com',
    phone: '123456789',
    name: 'Tiệc cưới',
    note: 'Ghi chú',
    number_of_guests: 600,
    organization_date: '2024-06-15T00:00:00.000Z',
    party_type_id: 1,
    shift: 'Sáng',
  },
  {
    user_id: 8,
    branch_id: 1,
    stage_id: 1,
    company_name: 'Công ty H',
    email: 'congtyh@gmail.com',
    phone: '123456789',
    name: 'Tiệc mừng thọ',
    note: 'Ghi chú',
    number_of_guests: 100,
    organization_date: '2024-07-20T00:00:00.000Z',
    party_type_id: 1,
    shift: 'Tối',
  },
  {
    user_id: 9,
    branch_id: 1,
    stage_id: 1,
    company_name: 'Công ty I',
    email: 'congtyi@gmail.com',
    phone: '123456789',
    name: 'Tiệc công ty',
    note: 'Ghi chú',
    number_of_guests: 350,
    organization_date: '2024-08-25T00:00:00.000Z',
    party_type_id: 1,
    shift: 'Sáng',
  },
  {
    user_id: 9,
    branch_id: 1,
    stage_id: 1,
    company_name: 'Công ty I',
    email: 'congtyi@gmail.com',
    phone: '123456789',
    name: 'Tiệc công ty',
    note: 'Ghi chú',
    number_of_guests: 350,
    organization_date: '2024-08-30T00:00:00.000Z',
    party_type_id: 1,
    shift: 'Sáng',
  },
  {
    user_id: 10,
    branch_id: 1,
    stage_id: 1,
    company_name: 'Công ty J',
    email: 'congtyj@gmail.com',
    phone: '123456789',
    name: 'Tiệc Halloween',
    note: 'Ghi chú',
    number_of_guests: 450,
    organization_date: '2024-09-10T00:00:00.000Z',
    party_type_id: 1,
    shift: 'Tối',
  },
  {
    user_id: 11,
    branch_id: 1,
    stage_id: 1,
    company_name: 'Công ty K',
    email: 'congtyk@gmail.com',
    phone: '123456789',
    name: 'Tiệc Tết',
    note: 'Ghi chú',
    number_of_guests: 700,
    organization_date: '2024-10-05T00:00:00.000Z',
    party_type_id: 1,
    shift: 'Sáng',
  },
  {
    user_id: 12,
    branch_id: 1,
    stage_id: 1,
    company_name: 'Công ty L',
    email: 'congtyl@gmail.com',
    phone: '123456789',
    name: 'Tiệc cuối năm',
    note: 'Ghi chú',
    number_of_guests: 800,
    organization_date: '2024-11-15T00:00:00.000Z',
    party_type_id: 1,
    shift: 'Tối',
  },
  {
    user_id: 13,
    branch_id: 1,
    stage_id: 1,
    company_name: 'Công ty M',
    email: 'congtym@gmail.com',
    phone: '123456789',
    name: 'Tiệc mừng sinh nhật',
    note: 'Ghi chú',
    number_of_guests: 200,
    organization_date: '2024-12-01T00:00:00.000Z',
    party_type_id: 1,
    shift: 'Sáng',
  },
  {
    user_id: 14,
    branch_id: 1,
    stage_id: 1,
    company_name: 'Công ty N',
    email: 'congtyn@gmail.com',
    phone: '123456789',
    name: 'Tiệc mừng thăng chức',
    note: 'Ghi chú',
    number_of_guests: 300,
    organization_date: '2024-12-10T00:00:00.000Z',
    party_type_id: 1,
    shift: 'Tối',
  },
  {
    user_id: 15,
    branch_id: 1,
    stage_id: 1,
    company_name: 'Công ty O',
    email: 'congtyo@gmail.com',
    phone: '123456789',
    name: 'Tiệc mừng tốt nghiệp',
    note: 'Ghi chú',
    number_of_guests: 400,
    organization_date: '2024-12-20T00:00:00.000Z',
    party_type_id: 1,
    shift: 'Sáng',
  },
  {
    user_id: 16,
    branch_id: 1,
    stage_id: 1,
    company_name: 'Công ty P',
    email: 'congtyp@gmail.com',
    phone: '123456789',
    name: 'Tiệc mừng năm mới',
    note: 'Ghi chú',
    number_of_guests: 500,
    organization_date: '2024-12-31T00:00:00.000Z',
    party_type_id: 1,
    shift: 'Tối',
  },
  {
    user_id: 17,
    branch_id: 1,
    stage_id: 1,
    company_name: 'Công ty Q',
    email: 'congtyq@gmail.com',
    phone: '123456789',
    name: 'Tiệc mừng ngày Quốc tế Phụ nữ',
    note: 'Ghi chú',
    number_of_guests: 250,
    organization_date: '2024-03-08T00:00:00.000Z',
    party_type_id: 1,
    shift: 'Sáng',
  },
  {
    user_id: 18,
    branch_id: 1,
    stage_id: 1,
    company_name: 'Công ty R',
    email: 'congtyr@gmail.com',
    phone: '123456789',
    name: 'Tiệc mừng ngày Quốc tế Lao động',
    note: 'Ghi chú',
    number_of_guests: 350,
    organization_date: '2024-05-01T00:00:00.000Z',
    party_type_id: 1,
    shift: 'Tối',
  },
];

const booking_details = [
  {
    booking_id: 1,
    stage_id: 1,
    space_id: 1,
    decor_id: 1,
    menu_id: 1,
    payment_method: 'momo',
    stage: ['ABC'],
    space: ['ABC'],
    decor: ['ABC'],
    menu: ['ABC'],
    extra_service: ['ABC'],
    images: ['ABC'],
    amount_booking: 10000000,
    fee: 10,
    total_amount: 110000000,
  },
  {
    booking_id: 2,
    stage_id: 1,
    space_id: 1,
    decor_id: 1,
    menu_id: 1,
    payment_method: 'momo',
    stage: ['ABC'],
    space: ['ABC'],
    decor: ['ABC'],
    menu: ['ABC'],
    extra_service: ['ABC'],
    images: ['ABC'],
    amount_booking: 10000000,
    fee: 10,
    total_amount: 110000000,
  },
  {
    booking_id: 3,
    stage_id: 1,
    space_id: 1,
    decor_id: 1,
    menu_id: 1,
    payment_method: 'momo',
    stage: ['ABC'],
    space: ['ABC'],
    decor: ['ABC'],
    menu: ['ABC'],
    extra_service: ['ABC'],
    images: ['ABC'],
    amount_booking: 10000000,
    fee: 10,
    total_amount: 110000000,
  },
  {
    booking_id: 4,
    stage_id: 1,
    space_id: 1,
    decor_id: 1,
    menu_id: 1,
    payment_method: 'momo',
    stage: ['ABC'],
    space: ['ABC'],
    decor: ['ABC'],
    menu: ['ABC'],
    extra_service: ['ABC'],
    images: ['ABC'],
    amount_booking: 10000000,
    fee: 10,
    total_amount: 110000000,
  },
  {
    booking_id: 5,
    stage_id: 1,
    space_id: 1,
    decor_id: 1,
    menu_id: 1,
    payment_method: 'momo',
    stage: ['ABC'],
    space: ['ABC'],
    decor: ['ABC'],
    menu: ['ABC'],
    extra_service: ['ABC'],
    images: ['ABC'],
    amount_booking: 10000000,
    fee: 10,
    total_amount: 110000000,
  },
  {
    booking_id: 6,
    stage_id: 1,
    space_id: 1,
    decor_id: 1,
    menu_id: 1,
    payment_method: 'momo',
    stage: ['ABC'],
    space: ['ABC'],
    decor: ['ABC'],
    menu: ['ABC'],
    extra_service: ['ABC'],
    images: ['ABC'],
    amount_booking: 10000000,
    fee: 10,
    total_amount: 110000000,
  },
  {
    booking_id: 7,
    stage_id: 1,
    space_id: 1,
    decor_id: 1,
    menu_id: 1,
    payment_method: 'momo',
    stage: ['ABC'],
    space: ['ABC'],
    decor: ['ABC'],
    menu: ['ABC'],
    extra_service: ['ABC'],
    images: ['ABC'],
    amount_booking: 10000000,
    fee: 10,
    total_amount: 110000000,
  },
  {
    booking_id: 8,
    stage_id: 1,
    space_id: 1,
    decor_id: 1,
    menu_id: 1,
    payment_method: 'momo',
    stage: ['ABC'],
    space: ['ABC'],
    decor: ['ABC'],
    menu: ['ABC'],
    extra_service: ['ABC'],
    images: ['ABC'],
    amount_booking: 10000000,
    fee: 10,
    total_amount: 110000000,
  },
  {
    booking_id: 9,
    stage_id: 1,
    space_id: 1,
    decor_id: 1,
    menu_id: 1,
    payment_method: 'momo',
    stage: ['ABC'],
    space: ['ABC'],
    decor: ['ABC'],
    menu: ['ABC'],
    extra_service: ['ABC'],
    images: ['ABC'],
    amount_booking: 10000000,
    fee: 10,
    total_amount: 110000000,
  },
  {
    booking_id: 10,
    stage_id: 1,
    space_id: 1,
    decor_id: 1,
    menu_id: 1,
    payment_method: 'momo',
    stage: ['ABC'],
    space: ['ABC'],
    decor: ['ABC'],
    menu: ['ABC'],
    extra_service: ['ABC'],
    images: ['ABC'],
    amount_booking: 10000000,
    fee: 10,
    total_amount: 110000000,
  },
  {
    booking_id: 11,
    stage_id: 1,
    space_id: 1,
    decor_id: 1,
    menu_id: 1,
    payment_method: 'momo',
    stage: ['ABC'],
    space: ['ABC'],
    decor: ['ABC'],
    menu: ['ABC'],
    extra_service: ['ABC'],
    images: ['ABC'],
    amount_booking: 10000000,
    fee: 10,
    total_amount: 110000000,
  },
  {
    booking_id: 12,
    stage_id: 1,
    space_id: 1,
    decor_id: 1,
    menu_id: 1,
    payment_method: 'momo',
    stage: ['ABC'],
    space: ['ABC'],
    decor: ['ABC'],
    menu: ['ABC'],
    extra_service: ['ABC'],
    images: ['ABC'],
    amount_booking: 10000000,
    fee: 10,
    total_amount: 110000000,
  },
  {
    booking_id: 13,
    stage_id: 1,
    space_id: 1,
    decor_id: 1,
    menu_id: 1,
    payment_method: 'momo',
    stage: ['ABC'],
    space: ['ABC'],
    decor: ['ABC'],
    menu: ['ABC'],
    extra_service: ['ABC'],
    images: ['ABC'],
    amount_booking: 10000000,
    fee: 10,
    total_amount: 110000000,
  },
  {
    booking_id: 14,
    stage_id: 1,
    space_id: 1,
    decor_id: 1,
    menu_id: 1,
    payment_method: 'momo',
    stage: ['ABC'],
    space: ['ABC'],
    decor: ['ABC'],
    menu: ['ABC'],
    extra_service: ['ABC'],
    images: ['ABC'],
    amount_booking: 10000000,
    fee: 10,
    total_amount: 110000000,
  },
  {
    booking_id: 15,
    stage_id: 1,
    space_id: 1,
    decor_id: 1,
    menu_id: 1,
    payment_method: 'momo',
    stage: ['ABC'],
    space: ['ABC'],
    decor: ['ABC'],
    menu: ['ABC'],
    extra_service: ['ABC'],
    images: ['ABC'],
    amount_booking: 10000000,
    fee: 10,
    total_amount: 110000000,
  },
  {
    booking_id: 16,
    stage_id: 1,
    space_id: 1,
    decor_id: 1,
    menu_id: 1,
    payment_method: 'momo',
    stage: ['ABC'],
    space: ['ABC'],
    decor: ['ABC'],
    menu: ['ABC'],
    extra_service: ['ABC'],
    images: ['ABC'],
    amount_booking: 10000000,
    fee: 10,
    total_amount: 110000000,
  },
  {
    booking_id: 17,
    stage_id: 1,
    space_id: 1,
    decor_id: 1,
    menu_id: 1,
    payment_method: 'momo',
    stage: ['ABC'],
    space: ['ABC'],
    decor: ['ABC'],
    menu: ['ABC'],
    extra_service: ['ABC'],
    images: ['ABC'],
    amount_booking: 10000000,
    fee: 10,
    total_amount: 110000000,
  },
  {
    booking_id: 18,
    stage_id: 1,
    space_id: 1,
    decor_id: 1,
    menu_id: 1,
    payment_method: 'momo',
    stage: ['ABC'],
    space: ['ABC'],
    decor: ['ABC'],
    menu: ['ABC'],
    extra_service: ['ABC'],
    images: ['ABC'],
    amount_booking: 10000000,
    fee: 10,
    total_amount: 110000000,
  },
];

export const bookingSeed = async () => {
  // for (let i = 0; i < booking.length; i++) {
  //   await prisma.bookings.create({
  //     data: booking[i],
  //   });
  // }

  for (let i = 6; i < booking_details.length; i++) {
    await prisma.booking_details.create({
      data: {
        booking_id: i,
        stage_id: booking_details[i].stage_id,
        space_id: booking_details[i].space_id,
        decor_id: booking_details[i].decor_id,
        menu_id: booking_details[i].menu_id,
        payment_method: 'momo',
        stage: booking_details[i].stage,
        amount_booking: booking_details[i].amount_booking,
        deposit_id: 1,
        fee: booking_details[i].fee,
        total_amount: booking_details[i].total_amount,
        menu: booking_details[i].menu,
        space: booking_details[i].space,
        decor: booking_details[i].decor,
        extra_service: booking_details[i].extra_service,
      } as any,
    });
  }
};
