name: Deploy NestJS to DigitalOcean
on:
  push:
    branches: [main]
    paths:
      - "server/**"
jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./server

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "./server/package-lock.json"

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            echo "Starting deployment..."

            # Navigate to project directory
            cd /var/www/JoiePalace/server

            # Pull latest changes
            echo "Pulling latest changes..."
            git pull origin main

            # Install dependencies
            echo "Installing dependencies..."
            npm install

            # Run Prisma Generate
            echo "Generating Prisma client..."
            npx prisma generate

            # Build application
            echo "Building application..."
            npm run build

            # PM2 process management
            echo "Managing PM2 process..."
            if pm2 list | grep -q "joieplace-api"; then
              pm2 reload joieplace-api
            else
              pm2 start dist/main.js --name joieplace-api
            fi

            # Save PM2 process list
            pm2 save

            echo "Deployment completed!"
