name: CICD Deploy Digital Ocean

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Connect and Find Directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            echo "Tìm kiếm thư mục JoiePalace..."
            FOLDER_PATH=$(find / -type d -name "JoiePalace" 2>/dev/null)
            echo "FOLDER_PATH=$FOLDER_PATH" >> $GITHUB_ENV
            echo "Kết quả tìm kiếm: $FOLDER_PATH"

      - name: Process Directory
        uses: appleboy/ssh-action@master
        if: env.FOLDER_PATH != ''
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            echo "Thư mục đã tìm thấy tại: $FOLDER_PATH"
            cd $FOLDER_PATH

            echo "Pulling changes..."
            git fetch origin
            git checkout main
            git pull origin main

      - name: Deploy Application
        uses: appleboy/ssh-action@master
        if: env.FOLDER_PATH != ''
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd $FOLDER_PATH/server

            echo "Installing dependencies..."
            npm ci

            echo "Generating Prisma..."
            npx prisma generate

            echo "Building..."
            npm run build

            echo "Reloading PM2..."
            pm2 reload server
