name: CICD Deploy Digital Ocean

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Connect and Find Directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            echo "Tìm kiếm thư mục JoiePalace..."
            FOLDER_PATH=$(find / -type d -name "JoiePalace" 2>/dev/null)
            echo "FOLDER_PATH=$FOLDER_PATH" >> $GITHUB_ENV
            echo "Kết quả tìm kiếm: $FOLDER_PATH"