name: CICD Deploy Digital Ocean

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch Latest Changes
        run: |
          echo "Fetching latest changes..."
          cd /JoiePalace
          git fetch origin || exit 1
          git checkout main || exit 1
          git pull origin main || exit 1

      - name: Install Server Dependencies
        run: |
          echo "Installing server dependencies..."
          cd /JoiePalace/server
          npm ci

      - name: Generate Prisma Client
        run: |
          echo "Generating Prisma client..."
          cd /JoiePalace/server
          npx prisma generate

      - name: Build the Application
        run: |
          echo "Building the application..."
          cd /JoiePalace/server
          npm run build

      - name: Reload PM2
        run: |
          echo "Reloading PM2..."
          pm2 reload server
