name: CICD Deploy Digital Ocean

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22

      - name: Fetch Latest Changes
        run: |
          echo "Fetching latest changes..."
          cd /***/JoiePalace
          git fetch origin || exit 1
          git checkout main || exit 1
          git pull origin main || exit 1

      - name: Install Server Dependencies
        run: |
          echo "Installing server dependencies..."
          cd /server
          npm ci

      - name: Generate Prisma Client
        run: |
          echo "Generating Prisma client..."
          cd /server
          npx prisma generate

      - name: Build the Application
        run: |
          echo "Building the application..."
          cd /server
          npm run build

      - name: Reload PM2
        run: |
          echo "Reloading PM2..."
          pm2 reload server
